# Generated by Django 4.2 on 2023-04-08 16:38

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#000000', image_field=None, max_length=18, null=True, samples=None),
        ),
    ]
