# Generated by Django 4.1.7 on 2023-03-05 12:21

import accounts.models.user
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.user.UserManager()),
            ],
        ),
    ]
